#!/bin/sh

ROFI=$(mpc -p 6601 playlist | rofi -dmenu -p 'Search : ')
if [ "$ROFI" = "" ]; then exit; fi
	POS=$(mpc -p 6601 playlist | grep -n "$ROFI" | awk -F: '{print $1}')
	mpc -p 6601 play $POS;
;;
